- name: Directories are created
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
    recurse: yes
    state: directory
  with_items: directories
  tags: [jenkins]

- name: Container is running
  docker:
    name: jenkins
    image: jenkins
    ports: 8080:8080
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /vagrant/.vagrant/machines:/machines
  register: container_result
  tags: [jenkins]

- name: Configurations are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: configs
  tags: [jenkins]

- name: Job directories are present
  file:
    path: "{{ home }}/jobs/{{ item }}"
    state: directory
    mode: "0777"
  with_items: jobs
  tags: [jenkins]

- name: Jobs are present
  copy:
    src: "{{ item }}.xml"
    dest: "{{ home }}/jobs/{{ item }}/config.xml"
  register: jobs_result
  with_items: jobs
  tags: [jenkins]

- name: Service job directories are present
  file:
    path: "{{ home }}/jobs/{{ item.service_name }}"
    state: directory
    mode: "0777"
  with_items: service_jobs
  tags: [jenkins]

- name: Plugins are installed
  shell: "curl -X POST \
    -d '<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>' \
    --header 'Content-Type: text/xml' \
    http://{{ ip }}:8080/pluginManager/installNecessaryPlugins"
  args:
    creates: /data/jenkins/plugins/{{ item }}.jpi
  with_items: plugins
  register: plugins_result
  tags: [jenkins]

- pause: minutes=1
  when: container_result|changed

- name: Container is restarted
  docker:
    name: jenkins
    image: jenkins
    state: restarted
  when: plugins_result|changed
  tags: [jenkins]

- pause: minutes=1
  when: plugins_result|changed

- name: Service jobs are present
  template:
    src: "service-config.xml"
    dest: "{{ home }}/jobs/{{ item.service_name }}/config.xml"
  with_items: service_jobs
  register: service_jobs_result
  tags: [jenkins]

- name: Jenkins is reloaded
  uri:
    url: http://{{ ip }}:8080/reload
    method: POST
  when: jobs_result|changed or service_jobs_result|changed
  ignore_errors: yes
  tags: [jenkins]
