- name: Directories are created
  file:
    path: /data/{{ service_name }}
    recurse: yes
    state: directory
  tags: [service, tests]

- name: Next color is retrieved
  shell: /data/{{ service_name }}/get-color.sh {{ service_name }}
  register: next_color
  tags: [service, tests]

- include: copy.yml

- name: Containers are pulled
  shell: docker-compose pull app-{{ next_color.stdout }}
  args:
    chdir: /data/{{ service_name }}
  tags: [service]

- name: Containers are running
  shell: docker-compose up -d app-{{ next_color.stdout }}
  args:
    chdir: /data/{{ service_name }}
  tags: [service]
