- name: Directories are created
  file:
    path: /data/{{ service_name }}
    recurse: yes
    state: directory
  tags: [service, tests]

- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: files
  tags: [service, tests]

- name: Next color is retrieved
  shell: /data/{{ service_name }}/get-color.sh {{ service_name }}
  register: next_color
  tags: [service, tests]

- name: Configs are updated
  replace:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items: replace
  tags: [service, tests]

- name: Containers are pulled
  shell: docker-compose pull app-{{ next_color.stdout }}
  args:
    chdir: /data/{{ service_name }}
  tags: [service]

- name: Containers are running
  shell: docker-compose up -d app-{{ next_color.stdout }}
  args:
    chdir: /data/{{ service_name }}
  tags: [service]

- name: Next port is retrieved
  shell: /data/{{ service_name }}/get-port.sh {{ next_color.stdout }}
  register: next_port
  tags: [service, tests]