- name: Directories are created
  file:
    path: /data/{{ service_name }}
    recurse: yes
    state: directory
  tags: [service]

- include: copy.yml

- name: Containers are pulled
  shell: docker-compose pull app-{{ next_color.stdout }}
  args:
    chdir: /data/{{ service_name }}
  tags: [service, pull]

- name: Containers are running
  shell: docker-compose rm -f app-{{ next_color.stdout }}
  args:
    chdir: /data/{{ service_name }}
  tags: [service]

- name: Containers are running
  shell: docker-compose up -d app-{{ next_color.stdout }}
  args:
    chdir: /data/{{ service_name }}
  tags: [service]
