- include: pre-deployment.yml

- include: deployment.yml

- include: post-deployment.yml

- include: rollback.yml

- name: Tests container is pushed
  shell: docker push \
    10.100.198.200:5000/{{ service_name }}-tests
  delegate_to: 127.0.0.1
  tags: [service, tests]
