- name: Next port is retrieved
  shell: /data/{{ service_name }}/get-port.sh {{ next_color.stdout }}
  register: next_port
  tags: [service, tests]

- name: Pre-integration tests are run
  shell: docker-compose \
    -f docker-compose-dev.yml \
    run --rm \
    -e DOMAIN={{ proxy_url }}:{{ next_port.stdout }} \
    integ
  args:
    chdir: "{{ repo_dir }}"
  register: pre_integ_result
  ignore_errors: yes
  delegate_to: 127.0.0.1
  tags: [service, tests]

- name: Proxy is configured
  shell: consul-template \
    -consul localhost:8500 \
    -template "{{ ct_src }}:{{ ct_dest }}:{{ ct_cmd }}" \
    -once
  when: pre_integ_result|success
  tags: [service]

- name: Post-integration tests are run
  shell: docker-compose \
    -f docker-compose-dev.yml \
    run --rm \
    -e DOMAIN={{ proxy_url }} \
    integ
  args:
    chdir: "{{ repo_dir }}"
  when: pre_integ_result|success
  register: post_integ_result
  ignore_errors: yes
  delegate_to: 127.0.0.1
  tags: [service, tests]

- name: Next color is put
  shell: curl -X PUT -d {{ next_color.stdout }} \
    localhost:8500/v1/kv/{{ service_name }}/color
  when: pre_integ_result|success and post_integ_result|success
  tags: [service, tests]

- name: Next color is retrieved
  shell: /data/{{ service_name }}/get-color.sh {{ service_name }}
  register: next_color
  tags: [service, tests]

- include: copy.yml

- name: Container is stopped
  shell: docker-compose stop app-{{ next_color.stdout }}
  args:
    chdir: /data/{{ service_name }}
  tags: [service]
