#- name: Pre-deployment tests failed
#  fail: msg="Simulation of pre-deployment tests failure"
#  delegate_to: 127.0.0.1
#  tags: [service, tests]

- name: Tests container is built
  shell: docker build \
    -t 10.100.198.200:5000/{{ service_name }}-tests \
    -f Dockerfile.test \
    .
  args:
    chdir: "{{ repo_dir }}"
  delegate_to: 127.0.0.1
  tags: [service, tests]

- name: Pre-deployment tests are run
  shell: docker-compose \
    -f docker-compose-dev.yml \
    run --rm tests
  args:
    chdir: "{{ repo_dir }}"
  delegate_to: 127.0.0.1
  tags: [service, tests]

- name: Container is built
  shell: docker build \
    -t 10.100.198.200:5000/{{ service_name }} \
    .
  args:
    chdir: "{{ repo_dir }}"
  delegate_to: 127.0.0.1
  tags: [service]

- name: Container is pushed
  shell: docker push \
    10.100.198.200:5000/{{ service_name }}
  delegate_to: 127.0.0.1
  tags: [service]
