files: [
  {
    src: "{{ repo_dir }}/docker-compose-swarm.ctmpl",
    dest: "/data/{{ service_name }}/docker-compose-swarm.ctmpl",
    mode: "0644"
  }, {
    src: "{{ repo_dir }}/nginx-includes.conf",
    dest: "/data/nginx/includes/{{ service_name }}.conf",
    mode: "0644"
  }, {
    src: "{{ repo_dir }}/nginx-upstreams.ctmpl",
    dest: "/data/nginx/upstreams/{{ service_name }}.ctmpl",
    mode: "0644"
  }, {
    src: "get-color.sh",
    dest: "/data/{{ service_name }}/get-color.sh",
    mode: "0755"
  }, {
    src: "get-domain.sh",
    dest: "/data/{{ service_name }}/get-domain.sh",
    mode: "0755"
  }
]

replace: [
  {
    dest: "/data/{{ service_name }}/docker-compose-swarm.ctmpl",
    regexp: "app:",
    replace: "app-{{ next_color.stdout }}:"
  }, {
    dest: "/data/{{ service_name }}/docker-compose-swarm.ctmpl",
    regexp: "SERVICE_NAME={{ service_name }}",
    replace: "SERVICE_NAME={{ service_name }}-{{ next_color.stdout }}"
  }, {
    dest: "/data/nginx/upstreams/{{ service_name }}.ctmpl",
    regexp: "range service \"{{ service_name }}\"",
    replace: "range service \"{{ service_name }}-{{ next_color.stdout }}\""
  }
]

ct_src: /data/nginx/upstreams/{{ service_name }}.ctmpl
ct_dest: /data/nginx/upstreams/{{ service_name }}.conf
ct_cmd: docker kill -s HUP nginx

ct_compose_src: /data/{{ service_name }}/docker-compose-swarm.ctmpl
ct_compose_dest: /data/{{ service_name }}/docker-compose.yml

scale_service: 1