files: [
  {
    src: "{{ repo_dir }}/docker-compose-swarm.yml",
    dest: "/data/{{ service_name }}/docker-compose.yml",
    mode: "0644"
  }, {
    src: "{{ repo_dir }}/nginx-includes.conf",
    dest: "/data/nginx/includes/{{ service_name }}.conf",
    mode: "0644"
  }, {
    src: "get-color.sh",
    dest: "/data/{{ service_name }}/get-color.sh",
    mode: "0755"
  }, {
    src: "get-domain.sh",
    dest: "/data/{{ service_name }}/get-domain.sh",
    mode: "0755"
  }
]

ct_src: /data/nginx/upstreams/{{ service_name }}.ctmpl
ct_dest: /data/nginx/upstreams/{{ service_name }}.conf
ct_cmd: docker kill -s HUP nginx

scale_service: 1