home: /data/jenkins
swarm_playbook: swarm-healing.yml

configs: [
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml" },
  { src: "cd-config.xml", dir: "/data/jenkins/nodes/cd", file: "config.xml" },
  { src: "prod-config.xml", dir: "/data/jenkins/nodes/prod", file: "config.xml" },
  { src: "swarm-master-config.xml", dir: "/data/jenkins/nodes/swarm-master", file: "config.xml" },
  { src: "LogParserPublisher.xml", dir: "/data/jenkins", file: "hudson.plugins.logparser.LogParserPublisher.xml" },
  { src: "parsing_rules", dir: "/data/jenkins", file: "parsing_rules" }
]

jobs: [
  {
    name: "books-ms-ansible",
    service_name: "books-ms",
    src: "service-ansible-config.xml"
  }, {
    name: "books-ms",
    service_name: "books-ms",
    src: "service-workflow-config.xml"
  }, {
    name: "books-ms-multibranch",
    service_name: "books-ms",
    src: "service-workflow-multibranch-config.xml"
  }, {
    name: "books-ms-redeploy",
    service_name: "books-ms",
    src: "service-redeploy-config.xml"
  }, {
     name: "hardware-notification",
     service_name: "books-ms",
     src: "hardware-notification-config.xml"
   }
]

plugins:
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
  - template-project