lines: [
  {
    regexp: '^export nodes=',
    line: 'export nodes=${nodes:-"vagrant@10.100.199.200 vagrant@10.100.199.201 vagrant@10.100.199.202"}'
  }, {
    regexp: '^export role=',
    line: 'export role="a i i"'
  }, {
    regexp: '^export NUM_MINIONS=',
    line: 'export NUM_MINIONS=${NUM_MINIONS:-2}'
  }
]