files: [
  {
    src: "{{ repo_dir }}/docker-compose.yml",
    dest: "/data/{{ service_name }}/docker-compose.yml"
  }, {
    src: "{{ repo_dir }}/nginx-includes.conf",
    dest: "/data/nginx/includes/{{ service_name }}.conf"
  }, {
    src: "{{ repo_dir }}/nginx-upstreams.ctmpl",
    dest: "/data/nginx/upstreams/{{ service_name }}.ctmpl"
  }, {
    src: "get-color.sh",
    dest: "/data/{{ service_name }}/get-color.sh",
    mode: "0755"
  }, {
    src: "get-port.sh",
    dest: "/data/{{ service_name }}/get-port.sh",
    mode: "0755"
  }
]

replace: [
  {
    dest: "/data/{{ service_name }}/docker-compose.yml",
    regexp: "app:",
    replace: "app-{{ next_color.stdout }}:"
  }, {
    dest: "/data/{{ service_name }}/docker-compose.yml",
    regexp: "SERVICE_NAME: {{ service_name }}",
    replace: "SERVICE_NAME: {{ service_name }}-{{ next_color.stdout }}"
  }, {
    dest: "/data/nginx/upstreams/{{ service_name }}.ctmpl",
    regexp: "range service \"{{ service_name }}\"",
    replace: "range service \"{{ service_name }}-{{ next_color.stdout }}\""
  }
]

ct_src: /data/nginx/upstreams/{{ service_name }}.ctmpl
ct_dest: /data/nginx/upstreams/{{ service_name }}.conf
ct_cmd: docker kill -s HUP nginx
