- name: Files are present
  copy:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
    mode: "0644"
  register: result
  with_items:
    - { src: "{{ repo_dir }}/nginx-includes.conf", dest: "/data/nginx/includes/{{ service_name }}.conf" }
    - { src: "{{ repo_dir }}/nginx-upstreams.conf", dest: "/data/nginx/upstreams/{{ service_name }}.conf" }
  tags: [nginx]

- name: Container is reloaded
  shell: docker kill -s HUP nginx
  when: result|changed
  tags: [nginx]

