- name: Docker Compose is present
  get_url:
    url: https://github.com/docker/compose/releases/download/1.3.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
  tags: [docker]

- name: Docker Compose permissions are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  tags: [docker]
