apiVersion: v1
kind: ReplicationController
metadata:
  name: books-ms-rc
spec:
  replicas: 2
  selector:
    app: books-ms
  template:
    metadata:
      labels:
        app: books-ms
    spec:
      containers:
      - name: books-ms
        image: 10.100.198.200:5000/books-ms
        ports:
        - containerPort: 8080
      - name: books-ms-db
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: books-ms-storage
          mountPath: /data/db
      volumes:
      - name: books-ms-storage
        emptyDir: {}
