- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: files
  tags: [service]

- name: Next color is retrieved
  shell: /data/{{ service_name }}/get-color.sh {{ service_name }}
  register: next_color
  tags: [service]

- name: Configs are updated
  replace:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items: replace
  tags: [service]