- name: Directories are created
  file:
    path: /data/{{ service_name }}
    recurse: yes
    state: directory
  tags: [service]

- include: copy.yml

- name: Containers are pulled
  shell: docker-compose pull app-{{ next_color.stdout }}
  environment:
    DOCKER_HOST: tcp://10.100.192.200:2375
  args:
    chdir: /data/{{ service_name }}
  tags: [service, pull]

- name: DB container is running
  shell: docker-compose --x-networking up -d db
  environment:
    DOCKER_HOST: tcp://10.100.192.200:2375
  args:
    chdir: /data/{{ service_name }}
  tags: [service]

- name: App container is removed
  shell: docker-compose rm -f app-{{ next_color.stdout }}
  environment:
    DOCKER_HOST: tcp://10.100.192.200:2375
  args:
    chdir: /data/{{ service_name }}
  tags: [service]

- name: App container is running
  shell: docker-compose scale --x-networking app-{{ next_color.stdout }}={{ scale_service }}
  environment:
    DOCKER_HOST: tcp://10.100.192.200:2375
  args:
    chdir: /data/{{ service_name }}
  tags: [service]
