- name: Current color is retrieved
  shell: curl http://localhost:8500/v1/kv/{{ service_name }}/color?raw
  register: next_color
  tags: [service, tests]

- include: copy.yml

- name: Proxy is configured
  shell: consul-template \
    -consul localhost:8500 \
    -template "{{ ct_src }}:{{ ct_dest }}:{{ ct_cmd }}" \
    -once
  tags: [service]
